de:
  languageName: German
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} JST Wollerau. All Rights Reserved."
  title: "JST Wollerau"
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Impressum"
      help_url: "/impressum/"
    ### calls to action ###
    main_cta:
      text: "Kontakt"
      link: "/kontakt/"
    github_edit: " "
  ### example menu showing children ###
  menu:
    main:
    - identifier: "Team"
      name: "Team"
      url: "/team/"
      weight: 1
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
